name: logros_puntuacion
version: '${project.version}'
main: org.captainlainist.logros_puntuacion.Logros_puntuacion
api-version: '1.20'
commands:
  score:
    description: See your score
    usage: /score
  givescore:
    description: Give or take away score
    usage: /givescore <player> <score>
    permission: logros_puntuacion.admin
  seescore:
    description: See other players score
    usage: /seescore <player>
    permission: logros_puntuacion.admin
  setscore:
    description: Set other players score
    usage: /setscore <player> <score>
    permission: logros_puntuacion.admin
permissions:
  logros_puntuacion.admin:
    description: Administrador
    default: op