name: logros_puntuacion
version: '1.0-SNAPSHOT'
main: org.captainlainist.logros_puntuacion.Logros_puntuacion
api-version: '1.20'
commands:
  puntos:
    description: Mira tus puntos
    usage: /puntos
  darpuntos:
    description: Dar o quitar puntos
    usage: /darpuntos <jugador> <puntos>
    permission: logros_puntuacion.admin
  verpuntos:
    description: ver puntos
    usage: /verpuntos <jugador>
    permission: logros_puntuacion.admin
  setpuntos:
    description: Imponer numero de puntos
    usage: /setpuntos <jugador> <puntos>
    permission: logros_puntuacion.admin
permissions:
  logros_puntuacion.admin:
    description: Administrador
    default: op